app/site/views.py
#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# Created by Roberto Preste
import requests
import json
from flask import Blueprint, render_template, flash, redirect, session, url_for, request, g, jsonify, send_file
from werkzeug.urls import url_parse

www = Blueprint("site", __name__)

from sqlalchemy import or_, and_
from app import app, db
from config import ADMINS
from flask_login import current_user, login_user, logout_user, login_required
from .forms import LoginForm, RegistrationForm
from .models import User
from app.static import dbdata


# Home Page
@www.route("/index", methods=["GET"])
@www.route("/home", methods=["GET"])
@www.route("/", methods=["GET"])
def index():
    return render_template("index.html",
                           title="My Database",
                           latest_update=dbdata.latest_update)


@www.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()

    if request.method == "GET":

        # expl: if user is already logged in, return to the home page
        if current_user.is_authenticated:
            return redirect(url_for("site.index"))

        return render_template("login.html", title="Log In", form=form)

    elif request.method == "POST":

        if form.validate_on_submit():
            user = User.query.filter(User.username == form.username.data).first()

            if not user.approved:
                flash("User not confirmed yet. Please wait for the approval email.")
                return redirect(url_for("site.index"))

            # expl: if user does not exist or the entered password is wrong
            if user is None or not user.check_password(form.password.data):
                flash("Invalid username or password!")
                return redirect(url_for("site.login"))

            login_user(user)
            user.update_last_access()
            next_page = request.args.get("next")

            # expl: check that the url sent is relative, to avoid external urls
            if not next_page or url_parse(next_page).netloc != "":
                next_page = "index"

            return redirect(url_for("site." + next_page.lstrip("/").lstrip("%252F")))


@www.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("site.index"))


@www.route("/register", methods=["GET", "POST"])
def register():
    form = RegistrationForm()

    if request.method == "GET":

        if current_user.is_authenticated:
            return redirect(url_for("site.index"))

        return render_template("register.html", title="Registration", form=form)

    elif request.method == "POST":

        # expl: a series of checks, since the internal ones don't seem to work properly
        if User.query.filter(User.email == form.email.data).first():
            flash("Email address already used. Please choose a different email address.")
            return redirect(url_for("site.register"))

        if User.query.filter(User.username == form.username.data).first():
            flash("Username existing. Please choose a different username.")
            return redirect(url_for("site.register"))

        if form.password.data != form.password2.data:
            flash("Passwords must match. Please check again. ")
            return redirect(url_for("site.register"))

        if form.validate_on_submit():

            user = User(username=form.username.data, email=form.email.data,
                        first_name=form.first_name.data, last_name=form.last_name.data)
            user.set_password(form.password.data)
            db.session.add(user)
            db.session.commit()
            send_email("[My Database]User {} registered.".format(form.username.data),
                       ADMINS[0],
                       [form.email.data, ADMINS[0]],
                       render_template("registr_request.txt",
                                       first_name=form.first_name.data,
                                       username=form.username.data,
                                       email=form.email.data))
            flash("Registration complete! You will be notified when your request is approved.")

            # expl: if the following lines are commented, approval is needed, using approve_user.py
            user.set_approval()
            send_email("[My Database] User {} approved".format(form.username.data),
                       ADMINS[0],
                       [form.email.data, ADMINS[0]],
                       render_template("registr_confirm.txt",
                                       first_name=form.first_name.data,
                                       username=form.username.data,
                                       email=form.email.data))

            return redirect(url_for("site.index"))


@www.errorhandler(404)
def page_not_found(e):
    return render_template("404.html", title="Error 404"), 404


@www.errorhandler(500)
def internal_server_error(e):
    return render_template("500.html", title="Error 500"), 500

app/templates/base.html
{% block doc -%}
<!DOCTYPE html>
<html{% block html_attribs %}{% endblock html_attribs %}>
{%- block html %}
    <head>
    {% block head %}

        <title>
        {% block title %}
            Insert title - {{ title|default }}
        {% endblock title %}
        </title>

        {%- block metas %}
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <meta charset="UTF-8">
        {%- endblock metas %}

        {%- block styles %}
            <!-- Bootstrap -->
            <link href="{{bootstrap_find_resource('css/bootstrap.css', cdn='bootstrap')}}" rel="stylesheet">
            <!-- Custom -->
            <link rel="stylesheet" href="{{ url_for('static', filename='css/stylesheet.css') }}">
            <!-- Favicon -->
            <link rel="icon" type="image/png" href="{{ url_for('static', filename='img/sample_favicon.png') }}" sizes="32x32">
        {%- endblock styles %}

    {% endblock head %}
    </head>

    <body>{% block body_attribs %}{% endblock body_attribs %}
    {% block body -%}
        <!-- Header -->
        <div class="container">

        <header class="row w3-margin">

            <!-- Main Header -->
            <div class="col-sm-12 w3-center">

                <a style="width: auto;" href="{{ url_for('site.index') }}" title="Insert title">
                    <img class="w3-hover-opacity w3-border w3-hover-border-blue w3-round-large" src="{{ url_for('static', filename = 'img/sample_banner.png') }}" alt="Insert title">
                </a>

            </div>

        </header>

        </div>

        <!-- Navigation Bar -->
        {% block navbar %}
            {% include "navigation.html" %}
        {% endblock navbar %}

        {% block content -%}
            <br><div class="container">&nbsp;</div><br><br> {# spacer! #}
            <footer class="footer">
                <div class="container">
                    <h6 class="text-muted">Copyright 2019 | Developed by <a href="https://robertopreste.com" title="Roberto Preste" target="_blank">Roberto Preste</a>.</h6>
                </div>
            </footer>
        {%- endblock content %}

        {% block scripts %}
            <!-- JQuery -->
            <script src="{{bootstrap_find_resource('jquery.js', cdn='jquery')}}"></script>
            <!-- Bootstrap -->
            <script src="{{bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap')}}"></script>
            <!-- Custom -->
            <script src="{{ url_for('static', filename='js/script.js') }}"></script>
        {% endblock scripts %}

        <!--<br /><br />-->
    {%- endblock body %}
    </body>

{%- endblock html %}
</html>
{% endblock doc -%}

app/templates/index.html
{% extends "base.html" %}

{% block content %}

    <div class="container">

    {% with messages = get_flashed_messages() %}
        {% if messages %}

            <div class="row" style="margin-top: 2em; margin-bottom: -3em;">

                <div class="col-sm-1">&nbsp;</div>

                <div class="col-sm-10 pulsanti w3-round-large" style="background-color: rgba(231,255,231,.6);">
                    <span class="w3-closebtn w3-text-teal w3-hover-text-indigo" onclick="this.parentElement.style.display='none'">&times;</span>
                    <br>
                    {% for message in messages %}
                    <p class="w3-center w3-text-indigo">{{ message }}</p>
                    {% endfor %}

                </div>

                <div class="col-sm-1">&nbsp;</div>

            </div>

        {% endif %}
    {% endwith %}

    <div class="row" style="margin-top: 4rem;">

        <div class="col-sm-2">&nbsp;</div>

        <div class="col-sm-8 w3-center" style="font-weight: bold;">

            <p class="w3-text-teal w3-xxlarge">Welcome!</p>
            <br />

            <p class="w3-text-indigo w3-large">This is a paragraph.</p>
            <br />

            <div class="row">

                <div class="col-sm-2">&nbsp;</div>

                <div class="col-sm-4 text-center">
                    <button class="pulsanti w3-hover-light-blue w3-hover-text-indigo w3-padding w3-round-large w3-xlarge" onclick="location.href='#'" title="Insert title">Test</button>
                </div>

                <div class="col-sm-4 text-center">
                    <button class="pulsanti w3-hover-light-blue w3-hover-text-indigo w3-padding w3-round-large w3-xlarge" onclick="location.href='{{ url_for('api.doc') }}'" title="API">API</button>
                </div>

                <div class="col-sm-2">&nbsp;</div>

            </div>

            <br />

        </div>

        <div class="col-sm-2">&nbsp;</div>

    </div>

    </div>

    {{ super() }}
{% endblock %}

app/templates/navigation.html
{% block navbar %}

    <div class="container">

    <div class="row">

        <div class="col-sm-12 w3-center">

            <button class="pulsanti w3-hover-light-blue w3-hover-text-indigo w3-padding w3-round-large" onclick="location.href='{{ url_for('site.index') }}'" title="Home">Home</button>
            {% if current_user.is_anonymous %}
            <button class="pulsanti w3-hover-light-blue w3-hover-text-indigo w3-padding w3-round-large" onclick="location.href='{{ url_for('site.login') }}'" title="Login">Login</button>
            {% else %}
            <button class="pulsanti w3-hover-light-blue w3-hover-text-indigo w3-padding w3-round-large" onclick="location.href='{{ url_for('site.logout') }}'" title="Logout">Logout</button>
            {% endif %}

        </div>

    </div>

    </div>

{% endblock %}